# Generated by Django 2.2 on 2020-07-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_message',
        ),
    ]
