# Generated by Django 2.2 on 2020-07-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_remove_comment_post_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='messages_app.Post'),
            preserve_default=False,
        ),
    ]
